<!doctype>
<html>
  <head>
    <title>2019 Fourth Quarter Report</title>
    <link href="styles.css" rel="stylesheet" media="all" />
  </head>
  <style>
    .page-break {
    page-break-after: always;
}
   .center {
  margin: auto;
  width: 50%;
  /* border: 3px solid green; */
  padding: 10px;
}
.centertm {
  margin-left: auto;
  margin-right: auto;
}
 .styled-table {
  border: 1px solid #369ed6;

    border-collapse: collapse;
    margin: 25px 0;
    font-size: 0.9em;
    font-family: sans-serif;
    min-width: 400px;
    box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
}
 .styled-tabletm {
  border: 1px solid #369ed6;

    border-collapse: collapse;
    font-size: 0.9em;
    font-family: sans-serif;
    min-width: 400px;
    box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
}
.styled-tabletm thead tr {
    background-color: #369ed6;
    color: #292929;
    font-size: 1em;
    /* text-align: left; */
}
.styled-table thead tr {
    background-color: #369ed6;
    color: #292929;
    font-size: 1em;
    /* text-align: left; */
}
.titl{
    
    font-size: 1.5em;
    background-color: #ffffff;
    /* text-align: left; */
}
.styled-table th,.styled-tabletm th,{
  text-align: center;
}

.styled-table th,
.styled-table td,.styled-tabletm th,
.styled-tabletm td {
    padding: 12px 15px;
}

.styled-table tbody tr, .styled-tabletm tbody tr  {
    border-bottom: 1px solid #dddddd;
    text-align: center
}

.styled-table tbody tr:nth-of-type(even),.styled-tabletm tbody tr:nth-of-type(even) {
    background-color: #f3f3f3;
}

.styled-table tbody tr:last-of-type,.styled-tabletm tbody tr:last-of-type {
    border-bottom: 2px solid #369ed6;
}
.styled-table tbody tr.active-row, .styled-tabletm tbody tr.active-row {
    font-weight: bold;
    color: #009879;
}
.container{
  display: flex;
}
.table-1{
margin-right: 20px;
}
.pageNum{
    text-align: left;
}
h1, h3{
    text-align: center;
}
    </style>
  <body >
      <p class="pageNum">Page 1</p>
    <h1>TNPS REPORT</h1>
    <h3>Date: {{date("F jS  Y")}}</h3>
    <h3>Time: {{date("h:i:s A")}}</h3>
    <h3>Generated By: Firstname Lastname</h3>
    <div class="container center">
    <table class="styled-table table-1">
      <thead>
          <tr>
              <th colspan="4" class="titl">Agent</th>
              {{-- <th>Points</th> --}}
          </tr>
          <tr>
              <th colspan="">RR</th>
              <th colspan="">NPS</th>
              <th colspan="">SR</th>
              <th colspan="">%</th>
          </tr>
      </thead>
      <tbody>
          <tr>
              <td>12</td>
              <td>60</td>
              <td>60</td>
              <td>60</td>
          </tr>
      </tbody>
  </table>
  {{--  --}}
    
  
  <table class="styled-table">
    <thead>
        <tr>
            <th colspan="4" class="titl">BOT</th>
            {{-- <th>Points</th> --}}
        </tr>
        <tr>
            <th colspan="">RR</th>
            <th colspan="">NPS</th>
            <th colspan="">SR</th>
            <th colspan="">%</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>12</td>
            <td>60</td>
            <td>60</td>
            <td>60</td>
        </tr>
    </tbody>
</table>
</div>
    <div class="container center">
    <table class="styled-table table-1">
      <thead>
          <tr>
              <th colspan="4" class="titl">CHAT</th>
              {{-- <th>Points</th> --}}
          </tr>
          <tr>
              <th colspan="">RR</th>
              <th colspan="">NPS</th>
              <th colspan="">SR</th>
              <th colspan="">%</th>
          </tr>
      </thead>
      <tbody>
          <tr>
              <td>12</td>
              <td>60</td>
              <td>60</td>
              <td>60</td>
          </tr>
      </tbody>
  </table>
  {{--  --}}
    
  
  <table class="styled-table">
    <thead>
        <tr>
            <th colspan="4" class="titl">IVR</th>
            {{-- <th>Points</th> --}}
        </tr>
        <tr>
            <th colspan="">RR</th>
            <th colspan="">NPS</th>
            <th colspan="">SR</th>
            <th colspan="">%</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>12</td>
            <td>60</td>
            <td>60</td>
            <td>60</td>
        </tr>
    </tbody>
</table>
</div>
<div class="page-break"></div>
<p class="pageNum">Page 2</p>
<table class="styled-tabletm centertm">
  <thead>
      <tr>
          <th colspan="3" class="titl">TRAFFIC MIX</th>
          {{-- <th>Points</th> --}}
      </tr>
      <tr>
          <th colspan="">TP</th>
          <th colspan="2">MOBILE</th>
      </tr>
  </thead>
  <tbody>
      <tr>
          <td>AGENT</td>
          <td>0</td>
          <td>0%</td>
      </tr>
      <tr>
          <td>BOT</td>
          <td>0</td>
          <td>0%</td>
      </tr>
      <tr>
          <td>CHAT</td>
          <td>0</td>
          <td>0%</td>
      </tr>
      <tr>
          <td>IVR</td>
          <td>0</td>
          <td>0%</td>
      </tr>
      <tr>
          <td>Social Media</td>
          <td>0</td>
          <td>0%</td>
      </tr>
      <tr>
          <td>Emails</td>
          <td>0</td>
          <td>0%</td>
      </tr>
      <tr>
          <td>NPS Total</td>
          <td>0</td>
          <td>0%</td>
      </tr>
      <tr>
          <td>Digital Index</td>
          <td>0%</td>
          <td></td>
      </tr>
  </tbody>
</table>
  </body>
</html>